- type: job
  id: CargoTechnician
  name: job-name-cargotech
  description: job-description-cargotech
  playTimeTracker: JobCargoTechnician
  startingGear: CargoTechGear
  icon: "CargoTechnician"
  supervisors: job-supervisors-hop-qm
  access:
  - Cargo
  - Maintenance
  - External
  minBankBalance: 300
  maxBankBalance: 500
  wageDepartment: Cargo
  wage: 100
  sponsorsOnly: true

- type: startingGear
  id: CargoTechGear
  equipment:
    head: ClothingHeadHatCargosoft
    jumpsuit: ClothingUniformJumpsuitCargo
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorBlack
    id: CargoPDA
    ears: ClothingHeadsetCargo
    pocket1: AppraisalTool
  innerclothingskirt: ClothingUniformJumpskirtCargo
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
